name       : rinutils
version    : 0.10.0
release    : 2
source     :
    - https://github.com/shlomif/rinutils/releases/download/0.10.0/rinutils-0.10.0.tar.xz : 70d89f0a8464f8f494f33704b7c9396e7fca392e8aafaa4465710c1a389e9806
license    : MIT
homepage   : https://www.shlomifish.org/open-source/projects/
component  : programming.library
summary    : C11 / gnu11 utilities C library
description: |
    C11 / gnu11 utilities C library
patterns   :
    - /*
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
