name       : rinutils
version    : 0.10.1
release    : 3
source     :
    - https://github.com/shlomif/rinutils/releases/download/0.10.1/rinutils-0.10.1.tar.xz : 31ec258ce99de7bbbe79f3338ce73048dac45425045eb2bd0d6bd92d1b8b9afb
license    : MIT
homepage   : https://www.shlomifish.org/open-source/projects/
component  : programming.library
summary    : C11 / gnu11 utilities C library
description: |
    C11 / gnu11 utilities C library
patterns   :
    - /*
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
