name       : rinutils
version    : 0.2.0
release    : 1
source     :
    - https://github.com/shlomif/rinutils/releases/download/0.2.0/rinutils-0.2.0.tar.xz : 2abcf60b99251f16f7a76827969cd626322f81f21500974deac4d1cff9f5c721
license    : MIT
homepage   : https://www.shlomifish.org/open-source/projects/
component  : programming.library
summary    : C11 / gnu11 utilities C library
description: |
    C11 / gnu11 utilities C library
builddeps  : 
    - pkgconfig(cmocka)
patterns   :
    - /usr/lib
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
